# Generated by Django 5.2.7 on 2025-10-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, help_text='Session start time')),
                ('ended_at', models.DateTimeField(help_text='Session end time')),
                ('duration_minutes', models.IntegerField(default=0, help_text='Session duration in minutes')),
                ('total_commits', models.IntegerField(default=0, help_text='Number of commits in session')),
                ('total_additions', models.IntegerField(default=0, help_text='Total lines added')),
                ('total_deletions', models.IntegerField(default=0, help_text='Total lines deleted')),
                ('files_changed', models.IntegerField(default=0, help_text='Number of unique files changed')),
                ('primary_language', models.CharField(blank=True, help_text='Most used programming language', max_length=50, null=True)),
                ('languages_used', models.JSONField(blank=True, default=list, help_text='List of all languages used')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated session narrative', null=True)),
                ('ai_generated_at', models.DateTimeField(blank=True, help_text='When AI summary was generated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coding Session',
                'verbose_name_plural': 'Coding Sessions',
                'db_table': 'coding_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(db_index=True, help_text='GitHub repository ID', unique=True)),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('full_name', models.CharField(help_text='Full repository name (owner/repo)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Repository description', null=True)),
                ('url', models.URLField(help_text='GitHub repository URL', max_length=500)),
                ('default_branch', models.CharField(default='main', help_text='Default branch name', max_length=100)),
                ('is_private', models.BooleanField(default=False, help_text='Is this a private repository?')),
                ('is_fork', models.BooleanField(default=False, help_text='Is this repository a fork?')),
                ('language', models.CharField(blank=True, help_text='Primary programming language', max_length=50, null=True)),
                ('stars_count', models.IntegerField(default=0, help_text='Number of stars')),
                ('forks_count', models.IntegerField(default=0, help_text='Number of forks')),
                ('is_tracking_enabled', models.BooleanField(default=True, help_text='Track commits from this repository?')),
                ('webhook_id', models.BigIntegerField(blank=True, help_text='GitHub webhook ID', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time we synced with GitHub', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this repository', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'db_table': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(db_index=True, help_text='Git commit SHA', max_length=40, unique=True)),
                ('message', models.TextField(help_text='Commit message')),
                ('author_name', models.CharField(help_text='Commit author name', max_length=255)),
                ('author_email', models.EmailField(help_text='Commit author email', max_length=254)),
                ('committed_at', models.DateTimeField(db_index=True, help_text='When the commit was made')),
                ('additions', models.IntegerField(default=0, help_text='Lines added')),
                ('deletions', models.IntegerField(default=0, help_text='Lines deleted')),
                ('changed_files', models.IntegerField(default=0, help_text='Number of files changed')),
                ('files_data', models.JSONField(blank=True, default=list, help_text='List of changed files with details')),
                ('branch', models.CharField(default='main', help_text='Branch name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, help_text='Coding session this commit belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='core_tracking.codingsession')),
                ('repository', models.ForeignKey(help_text='Repository this commit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core_tracking.githubrepository')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'db_table': 'commits',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.AddField(
            model_name='codingsession',
            name='repository',
            field=models.ForeignKey(blank=True, help_text='Repository where session occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core_tracking.githubrepository'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['user', '-created_at'], name='repositorie_user_id_6354be_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['github_id'], name='repositorie_github__59aed5_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['is_tracking_enabled'], name='repositorie_is_trac_ac0b4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together={('user', 'github_id')},
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', '-committed_at'], name='commits_reposit_cea2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['session', '-committed_at'], name='commits_session_907d14_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['sha'], name='commits_sha_ae771e_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['user', '-started_at'], name='coding_sess_user_id_02f4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['repository', '-started_at'], name='coding_sess_reposit_8fddf8_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['-started_at'], name='coding_sess_started_a6ab1d_idx'),
        ),
    ]
