# Generated by Django 4.2.25 on 2025-10-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('push', 'Push'), ('pull_request', 'Pull Request'), ('ping', 'Ping'), ('other', 'Other')], db_index=True, max_length=50)),
                ('repository_full_name', models.CharField(db_index=True, max_length=255)),
                ('delivery_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns the repository (resolved during processing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='webhook_eve_created_201dd9_idx'), models.Index(fields=['repository_full_name', '-created_at'], name='webhook_eve_reposit_7f5672_idx')],
            },
        ),
    ]
